### ISSUE TITLE
Rainmeter crashing on load

### ISSUE THREAD

**Issue by thorambar** [fvanroie/MqttPlugin#1]
Hi first of all thanks for developing this Plugin.

I compiled it using the latest VS version and copied the files after your instructions, rainmeter crashes with the following error when I try to use the code shown below.

**Error:**
Anwendung: Rainmeter.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Net.Sockets.SocketException
   bei System.Net.Sockets.Socket.DoConnect(System.Net.EndPoint, System.Net.SocketAddress)
   bei System.Net.Sockets.Socket.Connect(System.Net.EndPoint)
   bei uPLibrary.Networking.M2Mqtt.MqttNetworkChannel.Connect()
   bei uPLibrary.Networking.M2Mqtt.MqttClient.Connect(System.String, System.String, System.String, Boolean, Byte, Boolean, System.String, System.String, Boolean, UInt16)

Ausnahmeinformationen: uPLibrary.Networking.M2Mqtt.Exceptions.MqttConnectionException
   bei uPLibrary.Networking.M2Mqtt.MqttClient.Connect(System.String, System.String, System.String, Boolean, Byte, Boolean, System.String, System.String, Boolean, UInt16)
   bei uPLibrary.Networking.M2Mqtt.MqttClient.Connect(System.String, System.String, System.String)
   bei MqttPlugin.ParentMeasure.Reload(Rainmeter.API, Double ByRef)
   bei MqttPlugin.Plugin.Reload(IntPtr, IntPtr, Double ByRef)

**Code:**
[Rainmeter]
Update=1
BackgroundMode=2
SolidColor=000000

[mqttServer]
Measure=Plugin
Plugin=MqttPlugin.dll
Server=farmer.cloudmqtt.com
Username=*******
Password=*******
Port=16750

[mqttTopic1]
Measure=Plugin
Plugin=MqttPlugin.dll
ParentName=mqttServer
Topic=thermometer/data

[Text]
Meter=STRING
MeasureName=mqttServer
MeasureName2=mqttTopic1
X=5
Y=5
W=300
H=100
FontColor=FFFFFF
FontSize=24
Text="mqttServer: %1#CRLF#mqttTopic1: %2"

**Comment by fvanroie** [comment]
Hi @thorambar, thanks for your bug report.

I believe this is caused by the use of a non-standard port and/or lack of error-checking in the current version of the MqttPlugin. I'm testing on a local client with the default port... So, just now I updated the v0.0.2 branch with a some better error handling for connection failures:

- In v0.0.2 there is support for the `Port` parameter, v0.0.1 (current master) did not.
- Added better error handling for connection issues and verbosity in the Rainmeter Log.

Can you please pull the new v0.0.2 version and recompile? Only the MqttPlugin.dll needs to be updated. If you still see the error, please report back with the versions of Windows, .NET and Rainmeter you are using.

Hope this helps, let me know if it does or doesn't. I appreciate you taking the time to test the plug-in!

**Comment by thorambar** [comment]
Tried v0.0.2 worked without perfectly without any other changes. 
The update interval was so low from me playing around, but yeah 1ms is silly. 

Thanks again for your work this plugin is exactly what I was looking for and for taking the time to reply.

**Comment by fvanroie** [comment]
No problem, thanks for confirming the v0.0.2 update (f89470f) works. Glad to help out.
